<template>
    <!--当前城市切换移动端-->
    <div class="citySwitch" id="cs">
        <div class="innerCitySwitch">
            <div class="listCity">
                <div class="title">城市列表</div>
                <div class="innerContent">
                    <div class="item" v-for="(val, index) in letterToCity" :key="index">
                        <div class="lcTitle" :id="index">{{index}}</div>
                        <div class="lcContent" :id="`${index}-1`">
                            <div class="lcItem" v-for="(item, sIndex) in val" :key="sIndex" :data-id="item.id"
                                 :data-char="item.headChar">{{item.name}}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="letterGuide">
            <div class="innerLetter" @touchmove="letterGTMove">
                <div class="item" v-for="(item, index) in cityLetter" :key="index" :id="`${item}-2`"
                     @click="letterClick(item)">
                    {{item}}
                </div>
            </div>
        </div>
        <div class="letterActive">{{letterActive}}</div>
    </div>
</template>

<script>
    export default {
        name: 'citySwitch',
        data() {
            return {
                showLetterA: false,
                letterActive: 'A',
                cityLetter: [],
                letterToCity: {},
                offsetTops: [],
                letterOTS: [],
                cityD: [{
                    "headChar": "A",
                    "list": [{
                        "headChar": "A",
                        "name": "阿坝藏族羌族自治州",
                        "id": 291,
                        "name_ch": "ABaZangZuQiangZuZiZhiZhou",
                        "shortname_ch": "abzzqzzzz"
                    }, {
                        "headChar": "A",
                        "name": "安康市",
                        "id": 334,
                        "name_ch": "AnKangShi",
                        "shortname_ch": "aks"
                    }, {
                        "headChar": "A",
                        "name": "阿克苏地区",
                        "id": 370,
                        "name_ch": "AKeSuDiQu",
                        "shortname_ch": "aksdq"
                    }, {
                        "headChar": "A",
                        "name": "阿里地区",
                        "id": 324,
                        "name_ch": "ALiDiQu",
                        "shortname_ch": "aldq"
                    }, {
                        "headChar": "A",
                        "name": "阿拉善盟",
                        "id": 70,
                        "name_ch": "ALaShanMeng",
                        "shortname_ch": "alsm"
                    }, {
                        "headChar": "A",
                        "name": "阿勒泰地区",
                        "id": 376,
                        "name_ch": "ALeTaiDiQu",
                        "shortname_ch": "altdq"
                    }, {
                        "headChar": "A",
                        "name": "安庆市",
                        "id": 140,
                        "name_ch": "AnQingShi",
                        "shortname_ch": "aqs"
                    }, {
                        "headChar": "A",
                        "name": "安顺市",
                        "id": 297,
                        "name_ch": "AnShunShi",
                        "shortname_ch": "ass"
                    }, {
                        "headChar": "A",
                        "name": "鞍山市",
                        "id": 73,
                        "name_ch": "AnShanShi",
                        "shortname_ch": "ass"
                    }, {"headChar": "A", "name": "安阳市", "id": 191, "name_ch": "AnYangShi", "shortname_ch": "ays"}]
                }, {
                    "headChar": "B",
                    "list": [{
                        "headChar": "B",
                        "name": "蚌埠市",
                        "id": 135,
                        "name_ch": "BangBuShi",
                        "shortname_ch": "bbs"
                    }, {
                        "headChar": "B",
                        "name": "白城市",
                        "id": 92,
                        "name_ch": "BaiChengShi",
                        "shortname_ch": "bcs"
                    }, {
                        "headChar": "B",
                        "name": "保定市",
                        "id": 42,
                        "name_ch": "BaoDingShi",
                        "shortname_ch": "bds"
                    }, {
                        "headChar": "B",
                        "name": "博尔塔拉蒙古自治州",
                        "id": 368,
                        "name_ch": "BoErTaLaMengGuZiZhiZhou",
                        "shortname_ch": "betlmgzzz"
                    }, {
                        "headChar": "B",
                        "name": "北海市",
                        "id": 257,
                        "name_ch": "BeiHaiShi",
                        "shortname_ch": "bhs"
                    }, {
                        "headChar": "B",
                        "name": "毕节地区",
                        "id": 300,
                        "name_ch": "BiJieDiQu",
                        "shortname_ch": "bjdq"
                    }, {
                        "headChar": "B",
                        "name": "宝鸡市",
                        "id": 328,
                        "name_ch": "BaoJiShi",
                        "shortname_ch": "bjs"
                    }, {
                        "headChar": "B",
                        "name": "北京市",
                        "id": 377,
                        "name_ch": "BeiJingShi",
                        "shortname_ch": "bjs"
                    }, {
                        "headChar": "B",
                        "name": "百色市",
                        "id": 262,
                        "name_ch": "BaiSeShi",
                        "shortname_ch": "bss"
                    }, {
                        "headChar": "B",
                        "name": "保山市",
                        "id": 306,
                        "name_ch": "BaoShanShi",
                        "shortname_ch": "bss"
                    }, {
                        "headChar": "B",
                        "name": "白山市",
                        "id": 90,
                        "name_ch": "BaiShanShi",
                        "shortname_ch": "bss"
                    }, {
                        "headChar": "B",
                        "name": "包头市",
                        "id": 60,
                        "name_ch": "BaoTouShi",
                        "shortname_ch": "bts"
                    }, {
                        "headChar": "B",
                        "name": "本溪市",
                        "id": 75,
                        "name_ch": "BenXiShi",
                        "shortname_ch": "bxs"
                    }, {
                        "headChar": "B",
                        "name": "巴音郭楞蒙古自治州",
                        "id": 369,
                        "name_ch": "BaYinGuoLengMengGuZiZhiZhou",
                        "shortname_ch": "byglmgzzz"
                    }, {
                        "headChar": "B",
                        "name": "巴彦淖尔市",
                        "id": 66,
                        "name_ch": "BaYanNaoErShi",
                        "shortname_ch": "bynes"
                    }, {
                        "headChar": "B",
                        "name": "白银市",
                        "id": 339,
                        "name_ch": "BaiYinShi",
                        "shortname_ch": "bys"
                    }, {
                        "headChar": "B",
                        "name": "巴中市",
                        "id": 289,
                        "name_ch": "BaZhongShi",
                        "shortname_ch": "bzs"
                    }, {
                        "headChar": "B",
                        "name": "亳州市",
                        "id": 147,
                        "name_ch": "BoZhouShi",
                        "shortname_ch": "bzs"
                    }, {"headChar": "B", "name": "滨州市", "id": 185, "name_ch": "BinZhouShi", "shortname_ch": "bzs"}]
                }, {
                    "headChar": "C",
                    "list": [{
                        "headChar": "C",
                        "name": "昌都地区",
                        "id": 320,
                        "name_ch": "ChangDouDiQu",
                        "shortname_ch": "cddq"
                    }, {
                        "headChar": "C",
                        "name": "成都市",
                        "id": 273,
                        "name_ch": "ChengDouShi",
                        "shortname_ch": "cds"
                    }, {
                        "headChar": "C",
                        "name": "承德市",
                        "id": 44,
                        "name_ch": "ChengDeShi",
                        "shortname_ch": "cds"
                    }, {
                        "headChar": "C",
                        "name": "常德市",
                        "id": 224,
                        "name_ch": "ChangDeShi",
                        "shortname_ch": "cds"
                    }, {
                        "headChar": "C",
                        "name": "赤峰市",
                        "id": 62,
                        "name_ch": "ChiFengShi",
                        "shortname_ch": "cfs"
                    }, {
                        "headChar": "C",
                        "name": "巢湖市",
                        "id": 145,
                        "name_ch": "ChaoHuShi",
                        "shortname_ch": "chs"
                    }, {
                        "headChar": "C",
                        "name": "昌吉回族自治州",
                        "id": 367,
                        "name_ch": "ChangJiHuiZuZiZhiZhou",
                        "shortname_ch": "cjhzzzz"
                    }, {
                        "headChar": "C",
                        "name": "重庆市",
                        "id": 390,
                        "name_ch": "ChongQingShi",
                        "shortname_ch": "cqs"
                    }, {
                        "headChar": "C",
                        "name": "楚雄彝族自治州",
                        "id": 311,
                        "name_ch": "ChuXiongYiZuZiZhiZhou",
                        "shortname_ch": "cxyzzzz"
                    }, {
                        "headChar": "C",
                        "name": "朝阳市",
                        "id": 83,
                        "name_ch": "ChaoYangShi",
                        "shortname_ch": "cys"
                    }, {
                        "headChar": "C",
                        "name": "崇左市",
                        "id": 266,
                        "name_ch": "ChongZuoShi",
                        "shortname_ch": "czs"
                    }, {
                        "headChar": "C",
                        "name": "沧州市",
                        "id": 45,
                        "name_ch": "CangZhouShi",
                        "shortname_ch": "czs"
                    }, {
                        "headChar": "C",
                        "name": "常州市",
                        "id": 112,
                        "name_ch": "ChangZhouShi",
                        "shortname_ch": "czs"
                    }, {
                        "headChar": "C",
                        "name": "滁州市",
                        "id": 142,
                        "name_ch": "ChuZhouShi",
                        "shortname_ch": "czs"
                    }, {
                        "headChar": "C",
                        "name": "池州市",
                        "id": 148,
                        "name_ch": "ChiZhouShi",
                        "shortname_ch": "czs"
                    }, {
                        "headChar": "C",
                        "name": "郴州市",
                        "id": 227,
                        "name_ch": "ChenZhouShi",
                        "shortname_ch": "czs"
                    }, {"headChar": "C", "name": "潮州市", "id": 250, "name_ch": "ChaoZhouShi", "shortname_ch": "czs"}]
                }, {
                    "headChar": "D",
                    "list": [{
                        "headChar": "D",
                        "name": "丹东市",
                        "id": 76,
                        "name_ch": "DanDongShi",
                        "shortname_ch": "dds"
                    }, {
                        "headChar": "D",
                        "name": "东莞市",
                        "id": 248,
                        "name_ch": "DongGuanShi",
                        "shortname_ch": "dgs"
                    }, {
                        "headChar": "D",
                        "name": "德宏傣族景颇族自治州",
                        "id": 316,
                        "name_ch": "DeHongDaiZuJingPoZuZiZhiZhou",
                        "shortname_ch": "dhdzjpzzzz"
                    }, {
                        "headChar": "D",
                        "name": "大理白族自治州",
                        "id": 315,
                        "name_ch": "DaLiBaiZuZiZhiZhou",
                        "shortname_ch": "dlbzzzz"
                    }, {
                        "headChar": "D",
                        "name": "大连市",
                        "id": 72,
                        "name_ch": "DaLianShi",
                        "shortname_ch": "dls"
                    }, {
                        "headChar": "D",
                        "name": "大庆市",
                        "id": 99,
                        "name_ch": "DaQingShi",
                        "shortname_ch": "dqs"
                    }, {
                        "headChar": "D",
                        "name": "迪庆藏族自治州",
                        "id": 318,
                        "name_ch": "DiQingZangZuZiZhiZhou",
                        "shortname_ch": "dqzzzzz"
                    }, {
                        "headChar": "D",
                        "name": "大同市",
                        "id": 49,
                        "name_ch": "DaTongShi",
                        "shortname_ch": "dts"
                    }, {
                        "headChar": "D",
                        "name": "大兴安岭地区",
                        "id": 106,
                        "name_ch": "DaXingAnLingDiQu",
                        "shortname_ch": "dxaldq"
                    }, {
                        "headChar": "D",
                        "name": "定西市",
                        "id": 346,
                        "name_ch": "DingXiShi",
                        "shortname_ch": "dxs"
                    }, {
                        "headChar": "D",
                        "name": "德阳市",
                        "id": 277,
                        "name_ch": "DeYangShi",
                        "shortname_ch": "dys"
                    }, {
                        "headChar": "D",
                        "name": "东营市",
                        "id": 174,
                        "name_ch": "DongYingShi",
                        "shortname_ch": "dys"
                    }, {
                        "headChar": "D",
                        "name": "达州市",
                        "id": 287,
                        "name_ch": "DaZhouShi",
                        "shortname_ch": "dzs"
                    }, {"headChar": "D", "name": "德州市", "id": 183, "name_ch": "DeZhouShi", "shortname_ch": "dzs"}]
                }, {
                    "headChar": "E",
                    "list": [{
                        "headChar": "E",
                        "name": "鄂尔多斯市",
                        "id": 64,
                        "name_ch": "EErDuoSiShi",
                        "shortname_ch": "eedss"
                    }, {
                        "headChar": "E",
                        "name": "恩施土家族苗族自治州",
                        "id": 216,
                        "name_ch": "EnShiTuJiaZuMiaoZuZiZhiZhou",
                        "shortname_ch": "estjzmzzzz"
                    }, {"headChar": "E", "name": "鄂州市", "id": 209, "name_ch": "EZhouShi", "shortname_ch": "ezs"}]
                }, {
                    "headChar": "F",
                    "list": [{
                        "headChar": "F",
                        "name": "防城港市",
                        "id": 258,
                        "name_ch": "FangChengGangShi",
                        "shortname_ch": "fcgs"
                    }, {
                        "headChar": "F",
                        "name": "抚顺市",
                        "id": 74,
                        "name_ch": "FuShunShi",
                        "shortname_ch": "fss"
                    }, {
                        "headChar": "F",
                        "name": "佛山市",
                        "id": 237,
                        "name_ch": "FoShanShi",
                        "shortname_ch": "fss"
                    }, {
                        "headChar": "F",
                        "name": "阜新市",
                        "id": 79,
                        "name_ch": "FuXinShi",
                        "shortname_ch": "fxs"
                    }, {
                        "headChar": "F",
                        "name": "阜阳市",
                        "id": 143,
                        "name_ch": "FuYangShi",
                        "shortname_ch": "fys"
                    }, {
                        "headChar": "F",
                        "name": "福州市",
                        "id": 150,
                        "name_ch": "FuZhouShi",
                        "shortname_ch": "fzs"
                    }, {"headChar": "F", "name": "抚州市", "id": 168, "name_ch": "FuZhouShi", "shortname_ch": "fzs"}]
                }, {
                    "headChar": "G",
                    "list": [{
                        "headChar": "G",
                        "name": "广安市",
                        "id": 286,
                        "name_ch": "GuangAnShi",
                        "shortname_ch": "gas"
                    }, {
                        "headChar": "G",
                        "name": "贵港市",
                        "id": 260,
                        "name_ch": "GuiGangShi",
                        "shortname_ch": "ggs"
                    }, {
                        "headChar": "G",
                        "name": "桂林市",
                        "id": 255,
                        "name_ch": "GuiLinShi",
                        "shortname_ch": "gls"
                    }, {
                        "headChar": "G",
                        "name": "果洛藏族自治州",
                        "id": 355,
                        "name_ch": "GuoLuoZangZuZiZhiZhou",
                        "shortname_ch": "glzzzzz"
                    }, {
                        "headChar": "G",
                        "name": "甘南藏族自治州",
                        "id": 349,
                        "name_ch": "GanNanZangZuZiZhiZhou",
                        "shortname_ch": "gnzzzzz"
                    }, {
                        "headChar": "G",
                        "name": "广元市",
                        "id": 279,
                        "name_ch": "GuangYuanShi",
                        "shortname_ch": "gys"
                    }, {
                        "headChar": "G",
                        "name": "贵阳市",
                        "id": 294,
                        "name_ch": "GuiYangShi",
                        "shortname_ch": "gys"
                    }, {
                        "headChar": "G",
                        "name": "固原市",
                        "id": 361,
                        "name_ch": "GuYuanShi",
                        "shortname_ch": "gys"
                    }, {
                        "headChar": "G",
                        "name": "赣州市",
                        "id": 165,
                        "name_ch": "GanZhouShi",
                        "shortname_ch": "gzs"
                    }, {
                        "headChar": "G",
                        "name": "广州市",
                        "id": 232,
                        "name_ch": "GuangZhouShi",
                        "shortname_ch": "gzs"
                    }, {
                        "headChar": "G",
                        "name": "甘孜藏族自治州",
                        "id": 292,
                        "name_ch": "GanZiZangZuZiZhiZhou",
                        "shortname_ch": "gzzzzzz"
                    }]
                }, {
                    "headChar": "H",
                    "list": [{
                        "headChar": "H",
                        "name": "淮安市",
                        "id": 116,
                        "name_ch": "HuaiAnShi",
                        "shortname_ch": "has"
                    }, {
                        "headChar": "H",
                        "name": "淮北市",
                        "id": 138,
                        "name_ch": "HuaiBeiShi",
                        "shortname_ch": "hbs"
                    }, {
                        "headChar": "H",
                        "name": "鹤壁市",
                        "id": 192,
                        "name_ch": "HeBiShi",
                        "shortname_ch": "hbs"
                    }, {
                        "headChar": "H",
                        "name": "海北藏族自治州",
                        "id": 352,
                        "name_ch": "HaiBeiZangZuZiZhiZhou",
                        "shortname_ch": "hbzzzzz"
                    }, {
                        "headChar": "H",
                        "name": "河池市",
                        "id": 264,
                        "name_ch": "HeChiShi",
                        "shortname_ch": "hcs"
                    }, {
                        "headChar": "H",
                        "name": "海东地区",
                        "id": 351,
                        "name_ch": "HaiDongDiQu",
                        "shortname_ch": "hddq"
                    }, {
                        "headChar": "H",
                        "name": "邯郸市",
                        "id": 40,
                        "name_ch": "HanDanShi",
                        "shortname_ch": "hds"
                    }, {
                        "headChar": "H",
                        "name": "哈尔滨市",
                        "id": 94,
                        "name_ch": "HaErBinShi",
                        "shortname_ch": "hebs"
                    }, {
                        "headChar": "H",
                        "name": "合肥市",
                        "id": 133,
                        "name_ch": "HeFeiShi",
                        "shortname_ch": "hfs"
                    }, {
                        "headChar": "H",
                        "name": "鹤岗市",
                        "id": 97,
                        "name_ch": "HeGangShi",
                        "shortname_ch": "hgs"
                    }, {
                        "headChar": "H",
                        "name": "黄冈市",
                        "id": 213,
                        "name_ch": "HuangGangShi",
                        "shortname_ch": "hgs"
                    }, {
                        "headChar": "H",
                        "name": "红河哈尼族彝族自治州",
                        "id": 312,
                        "name_ch": "HongHeHaNiZuYiZuZiZhiZhou",
                        "shortname_ch": "hhhnzyzzzz"
                    }, {
                        "headChar": "H",
                        "name": "呼和浩特市",
                        "id": 59,
                        "name_ch": "HuHeHaoTeShi",
                        "shortname_ch": "hhhts"
                    }, {
                        "headChar": "H",
                        "name": "黑河市",
                        "id": 104,
                        "name_ch": "HeiHeShi",
                        "shortname_ch": "hhs"
                    }, {
                        "headChar": "H",
                        "name": "怀化市",
                        "id": 229,
                        "name_ch": "HuaiHuaShi",
                        "shortname_ch": "hhs"
                    }, {
                        "headChar": "H",
                        "name": "海口市",
                        "id": 267,
                        "name_ch": "HaiKouShi",
                        "shortname_ch": "hks"
                    }, {
                        "headChar": "H",
                        "name": "呼伦贝尔市",
                        "id": 65,
                        "name_ch": "HuLunBeiErShi",
                        "shortname_ch": "hlbes"
                    }, {
                        "headChar": "H",
                        "name": "葫芦岛市",
                        "id": 84,
                        "name_ch": "HuLuDaoShi",
                        "shortname_ch": "hlds"
                    }, {
                        "headChar": "H",
                        "name": "哈密地区",
                        "id": 366,
                        "name_ch": "HaMiDiQu",
                        "shortname_ch": "hmdq"
                    }, {
                        "headChar": "H",
                        "name": "淮南市",
                        "id": 136,
                        "name_ch": "HuaiNanShi",
                        "shortname_ch": "hns"
                    }, {
                        "headChar": "H",
                        "name": "黄南藏族自治州",
                        "id": 353,
                        "name_ch": "HuangNanZangZuZiZhiZhou",
                        "shortname_ch": "hnzzzzz"
                    }, {
                        "headChar": "H",
                        "name": "海南藏族自治州",
                        "id": 354,
                        "name_ch": "HaiNanZangZuZiZhiZhou",
                        "shortname_ch": "hnzzzzz"
                    }, {
                        "headChar": "H",
                        "name": "衡水市",
                        "id": 47,
                        "name_ch": "HengShuiShi",
                        "shortname_ch": "hss"
                    }, {
                        "headChar": "H",
                        "name": "黄山市",
                        "id": 141,
                        "name_ch": "HuangShanShi",
                        "shortname_ch": "hss"
                    }, {
                        "headChar": "H",
                        "name": "黄石市",
                        "id": 205,
                        "name_ch": "HuangShiShi",
                        "shortname_ch": "hss"
                    }, {
                        "headChar": "H",
                        "name": "和田地区",
                        "id": 373,
                        "name_ch": "HeTianDiQu",
                        "shortname_ch": "htdq"
                    }, {
                        "headChar": "H",
                        "name": "海西蒙古族藏族自治州",
                        "id": 357,
                        "name_ch": "HaiXiMengGuZuZangZuZiZhiZhou",
                        "shortname_ch": "hxmgzzzzzz"
                    }, {
                        "headChar": "H",
                        "name": "衡阳市",
                        "id": 221,
                        "name_ch": "HengYangShi",
                        "shortname_ch": "hys"
                    }, {
                        "headChar": "H",
                        "name": "河源市",
                        "id": 245,
                        "name_ch": "HeYuanShi",
                        "shortname_ch": "hys"
                    }, {
                        "headChar": "H",
                        "name": "贺州市",
                        "id": 263,
                        "name_ch": "HeZhouShi",
                        "shortname_ch": "hzs"
                    }, {
                        "headChar": "H",
                        "name": "汉中市",
                        "id": 332,
                        "name_ch": "HanZhongShi",
                        "shortname_ch": "hzs"
                    }, {
                        "headChar": "H",
                        "name": "杭州市",
                        "id": 122,
                        "name_ch": "HangZhouShi",
                        "shortname_ch": "hzs"
                    }, {
                        "headChar": "H",
                        "name": "湖州市",
                        "id": 126,
                        "name_ch": "HuZhouShi",
                        "shortname_ch": "hzs"
                    }, {
                        "headChar": "H",
                        "name": "菏泽市",
                        "id": 186,
                        "name_ch": "HeZeShi",
                        "shortname_ch": "hzs"
                    }, {"headChar": "H", "name": "惠州市", "id": 242, "name_ch": "HuiZhouShi", "shortname_ch": "hzs"}]
                }, {
                    "headChar": "J",
                    "list": [{
                        "headChar": "J",
                        "name": "吉安市",
                        "id": 166,
                        "name_ch": "JiAnShi",
                        "shortname_ch": "jas"
                    }, {
                        "headChar": "J",
                        "name": "晋城市",
                        "id": 52,
                        "name_ch": "JinChengShi",
                        "shortname_ch": "jcs"
                    }, {
                        "headChar": "J",
                        "name": "金昌市",
                        "id": 338,
                        "name_ch": "JinChangShi",
                        "shortname_ch": "jcs"
                    }, {
                        "headChar": "J",
                        "name": "景德镇市",
                        "id": 160,
                        "name_ch": "JingDeZhenShi",
                        "shortname_ch": "jdzs"
                    }, {
                        "headChar": "J",
                        "name": "金华市",
                        "id": 128,
                        "name_ch": "JinHuaShi",
                        "shortname_ch": "jhs"
                    }, {
                        "headChar": "J",
                        "name": "九江市",
                        "id": 162,
                        "name_ch": "JiuJiangShi",
                        "shortname_ch": "jjs"
                    }, {
                        "headChar": "J",
                        "name": "吉林市",
                        "id": 86,
                        "name_ch": "JiLinShi",
                        "shortname_ch": "jls"
                    }, {
                        "headChar": "J",
                        "name": "荆门市",
                        "id": 210,
                        "name_ch": "JingMenShi",
                        "shortname_ch": "jms"
                    }, {
                        "headChar": "J",
                        "name": "江门市",
                        "id": 238,
                        "name_ch": "JiangMenShi",
                        "shortname_ch": "jms"
                    }, {
                        "headChar": "J",
                        "name": "佳木斯市",
                        "id": 101,
                        "name_ch": "JiaMuSiShi",
                        "shortname_ch": "jmss"
                    }, {
                        "headChar": "J",
                        "name": "济南市",
                        "id": 170,
                        "name_ch": "JiNanShi",
                        "shortname_ch": "jns"
                    }, {
                        "headChar": "J",
                        "name": "济宁市",
                        "id": 177,
                        "name_ch": "JiNingShi",
                        "shortname_ch": "jns"
                    }, {
                        "headChar": "J",
                        "name": "酒泉市",
                        "id": 344,
                        "name_ch": "JiuQuanShi",
                        "shortname_ch": "jqs"
                    }, {
                        "headChar": "J",
                        "name": "鸡西市",
                        "id": 96,
                        "name_ch": "JiXiShi",
                        "shortname_ch": "jxs"
                    }, {
                        "headChar": "J",
                        "name": "嘉兴市",
                        "id": 125,
                        "name_ch": "JiaXingShi",
                        "shortname_ch": "jxs"
                    }, {
                        "headChar": "J",
                        "name": "嘉峪关市",
                        "id": 337,
                        "name_ch": "JiaYuGuanShi",
                        "shortname_ch": "jygs"
                    }, {
                        "headChar": "J",
                        "name": "揭阳市",
                        "id": 251,
                        "name_ch": "JieYangShi",
                        "shortname_ch": "jys"
                    }, {
                        "headChar": "J",
                        "name": "晋中市",
                        "id": 54,
                        "name_ch": "JinZhongShi",
                        "shortname_ch": "jzs"
                    }, {
                        "headChar": "J",
                        "name": "锦州市",
                        "id": 77,
                        "name_ch": "JinZhouShi",
                        "shortname_ch": "jzs"
                    }, {
                        "headChar": "J",
                        "name": "焦作市",
                        "id": 194,
                        "name_ch": "JiaoZuoShi",
                        "shortname_ch": "jzs"
                    }, {"headChar": "J", "name": "荆州市", "id": 212, "name_ch": "JingZhouShi", "shortname_ch": "jzs"}]
                }, {
                    "headChar": "K",
                    "list": [{
                        "headChar": "K",
                        "name": "开封市",
                        "id": 188,
                        "name_ch": "KaiFengShi",
                        "shortname_ch": "kfs"
                    }, {
                        "headChar": "K",
                        "name": "克拉玛依市",
                        "id": 364,
                        "name_ch": "KeLaMaYiShi",
                        "shortname_ch": "klmys"
                    }, {
                        "headChar": "K",
                        "name": "昆明市",
                        "id": 303,
                        "name_ch": "KunMingShi",
                        "shortname_ch": "kms"
                    }, {
                        "headChar": "K",
                        "name": "喀什地区",
                        "id": 372,
                        "name_ch": "KaShenDiQu",
                        "shortname_ch": "ksdq"
                    }, {
                        "headChar": "K",
                        "name": "克孜勒苏柯尔克孜自治州",
                        "id": 371,
                        "name_ch": "KeZiLeSuKeErKeZiZiZhiZhou",
                        "shortname_ch": "kzlskekzzzz"
                    }]
                }, {
                    "headChar": "L",
                    "list": [{
                        "headChar": "L",
                        "name": "六安市",
                        "id": 146,
                        "name_ch": "LiuAnShi",
                        "shortname_ch": "las"
                    }, {
                        "headChar": "L",
                        "name": "来宾市",
                        "id": 265,
                        "name_ch": "LaiBinShi",
                        "shortname_ch": "lbs"
                    }, {
                        "headChar": "L",
                        "name": "临沧市",
                        "id": 310,
                        "name_ch": "LinCangShi",
                        "shortname_ch": "lcs"
                    }, {
                        "headChar": "L",
                        "name": "聊城市",
                        "id": 184,
                        "name_ch": "LiaoChengShi",
                        "shortname_ch": "lcs"
                    }, {
                        "headChar": "L",
                        "name": "娄底市",
                        "id": 230,
                        "name_ch": "LouDiShi",
                        "shortname_ch": "lds"
                    }, {
                        "headChar": "L",
                        "name": "廊坊市",
                        "id": 46,
                        "name_ch": "LangFangShi",
                        "shortname_ch": "lfs"
                    }, {
                        "headChar": "L",
                        "name": "临汾市",
                        "id": 57,
                        "name_ch": "LinFenShi",
                        "shortname_ch": "lfs"
                    }, {
                        "headChar": "L",
                        "name": "漯河市",
                        "id": 197,
                        "name_ch": "LuoHeShi",
                        "shortname_ch": "lhs"
                    }, {
                        "headChar": "L",
                        "name": "丽江市",
                        "id": 308,
                        "name_ch": "LiJiangShi",
                        "shortname_ch": "ljs"
                    }, {
                        "headChar": "L",
                        "name": "吕梁市",
                        "id": 58,
                        "name_ch": "Lu:LiangShi",
                        "shortname_ch": "lls"
                    }, {
                        "headChar": "L",
                        "name": "陇南市",
                        "id": 347,
                        "name_ch": "LongNanShi",
                        "shortname_ch": "lns"
                    }, {
                        "headChar": "L",
                        "name": "六盘水市",
                        "id": 295,
                        "name_ch": "LiuPanShuiShi",
                        "shortname_ch": "lpss"
                    }, {
                        "headChar": "L",
                        "name": "乐山市",
                        "id": 282,
                        "name_ch": "LeShanShi",
                        "shortname_ch": "lss"
                    }, {
                        "headChar": "L",
                        "name": "拉萨市",
                        "id": 319,
                        "name_ch": "LaSaShi",
                        "shortname_ch": "lss"
                    }, {
                        "headChar": "L",
                        "name": "丽水市",
                        "id": 132,
                        "name_ch": "LiShuiShi",
                        "shortname_ch": "lss"
                    }, {
                        "headChar": "L",
                        "name": "凉山彝族自治州",
                        "id": 293,
                        "name_ch": "LiangShanYiZuZiZhiZhou",
                        "shortname_ch": "lsyzzzz"
                    }, {
                        "headChar": "L",
                        "name": "莱芜市",
                        "id": 181,
                        "name_ch": "LaiWuShi",
                        "shortname_ch": "lws"
                    }, {
                        "headChar": "L",
                        "name": "临夏回族自治州",
                        "id": 348,
                        "name_ch": "LinXiaHuiZuZiZhiZhou",
                        "shortname_ch": "lxhzzzz"
                    }, {
                        "headChar": "L",
                        "name": "连云港市",
                        "id": 115,
                        "name_ch": "LianYunGangShi",
                        "shortname_ch": "lygs"
                    }, {
                        "headChar": "L",
                        "name": "辽阳市",
                        "id": 80,
                        "name_ch": "LiaoYangShi",
                        "shortname_ch": "lys"
                    }, {
                        "headChar": "L",
                        "name": "辽源市",
                        "id": 88,
                        "name_ch": "LiaoYuanShi",
                        "shortname_ch": "lys"
                    }, {
                        "headChar": "L",
                        "name": "龙岩市",
                        "id": 157,
                        "name_ch": "LongYanShi",
                        "shortname_ch": "lys"
                    }, {
                        "headChar": "L",
                        "name": "临沂市",
                        "id": 182,
                        "name_ch": "LinYiShi",
                        "shortname_ch": "lys"
                    }, {
                        "headChar": "L",
                        "name": "洛阳市",
                        "id": 189,
                        "name_ch": "LuoYangShi",
                        "shortname_ch": "lys"
                    }, {
                        "headChar": "L",
                        "name": "林芝地区",
                        "id": 325,
                        "name_ch": "LinZhiDiQu",
                        "shortname_ch": "lzdq"
                    }, {
                        "headChar": "L",
                        "name": "泸州市",
                        "id": 276,
                        "name_ch": "LuZhouShi",
                        "shortname_ch": "lzs"
                    }, {
                        "headChar": "L",
                        "name": "兰州市",
                        "id": 336,
                        "name_ch": "LanZhouShi",
                        "shortname_ch": "lzs"
                    }, {"headChar": "L", "name": "柳州市", "id": 254, "name_ch": "LiuZhouShi", "shortname_ch": "lzs"}]
                }, {
                    "headChar": "M",
                    "list": [{
                        "headChar": "M",
                        "name": "马鞍山市",
                        "id": 137,
                        "name_ch": "MaAnShanShi",
                        "shortname_ch": "mass"
                    }, {
                        "headChar": "M",
                        "name": "牡丹江市",
                        "id": 103,
                        "name_ch": "MuDanJiangShi",
                        "shortname_ch": "mdjs"
                    }, {
                        "headChar": "M",
                        "name": "茂名市",
                        "id": 240,
                        "name_ch": "MaoMingShi",
                        "shortname_ch": "mms"
                    }, {
                        "headChar": "M",
                        "name": "眉山市",
                        "id": 284,
                        "name_ch": "MeiShanShi",
                        "shortname_ch": "mss"
                    }, {
                        "headChar": "M",
                        "name": "绵阳市",
                        "id": 278,
                        "name_ch": "MianYangShi",
                        "shortname_ch": "mys"
                    }, {"headChar": "M", "name": "梅州市", "id": 243, "name_ch": "MeiZhouShi", "shortname_ch": "mzs"}]
                }, {
                    "headChar": "N",
                    "list": [{
                        "headChar": "N",
                        "name": "宁波市",
                        "id": 123,
                        "name_ch": "NingBoShi",
                        "shortname_ch": "nbs"
                    }, {
                        "headChar": "N",
                        "name": "南充市",
                        "id": 283,
                        "name_ch": "NanChongShi",
                        "shortname_ch": "ncs"
                    }, {
                        "headChar": "N",
                        "name": "南昌市",
                        "id": 159,
                        "name_ch": "NanChangShi",
                        "shortname_ch": "ncs"
                    }, {
                        "headChar": "N",
                        "name": "宁德市",
                        "id": 158,
                        "name_ch": "NingDeShi",
                        "shortname_ch": "nds"
                    }, {
                        "headChar": "N",
                        "name": "怒江傈僳族自治州",
                        "id": 317,
                        "name_ch": "NuJiangLiSuZuZiZhiZhou",
                        "shortname_ch": "njlszzzz"
                    }, {
                        "headChar": "N",
                        "name": "内江市",
                        "id": 281,
                        "name_ch": "NeiJiangShi",
                        "shortname_ch": "njs"
                    }, {
                        "headChar": "N",
                        "name": "南京市",
                        "id": 109,
                        "name_ch": "NanJingShi",
                        "shortname_ch": "njs"
                    }, {
                        "headChar": "N",
                        "name": "南宁市",
                        "id": 253,
                        "name_ch": "NanNingShi",
                        "shortname_ch": "nns"
                    }, {
                        "headChar": "N",
                        "name": "南平市",
                        "id": 156,
                        "name_ch": "NanPingShi",
                        "shortname_ch": "nps"
                    }, {
                        "headChar": "N",
                        "name": "那曲地区",
                        "id": 323,
                        "name_ch": "NeiQuDiQu",
                        "shortname_ch": "nqdq"
                    }, {
                        "headChar": "N",
                        "name": "南通市",
                        "id": 114,
                        "name_ch": "NanTongShi",
                        "shortname_ch": "nts"
                    }, {"headChar": "N", "name": "南阳市", "id": 199, "name_ch": "NanYangShi", "shortname_ch": "nys"}]
                }, {
                    "headChar": "P",
                    "list": [{
                        "headChar": "P",
                        "name": "平顶山市",
                        "id": 190,
                        "name_ch": "PingDingShanShi",
                        "shortname_ch": "pdss"
                    }, {
                        "headChar": "P",
                        "name": "普洱市",
                        "id": 309,
                        "name_ch": "PuErShi",
                        "shortname_ch": "pes"
                    }, {
                        "headChar": "P",
                        "name": "盘锦市",
                        "id": 81,
                        "name_ch": "PanJinShi",
                        "shortname_ch": "pjs"
                    }, {
                        "headChar": "P",
                        "name": "平凉市",
                        "id": 343,
                        "name_ch": "PingLiangShi",
                        "shortname_ch": "pls"
                    }, {
                        "headChar": "P",
                        "name": "莆田市",
                        "id": 152,
                        "name_ch": "PuTianShi",
                        "shortname_ch": "pts"
                    }, {
                        "headChar": "P",
                        "name": "萍乡市",
                        "id": 161,
                        "name_ch": "PingXiangShi",
                        "shortname_ch": "pxs"
                    }, {
                        "headChar": "P",
                        "name": "濮阳市",
                        "id": 195,
                        "name_ch": "PuYangShi",
                        "shortname_ch": "pys"
                    }, {
                        "headChar": "P",
                        "name": "攀枝花市",
                        "id": 275,
                        "name_ch": "PanZhiHuaShi",
                        "shortname_ch": "pzhs"
                    }]
                }, {
                    "headChar": "Q",
                    "list": [{
                        "headChar": "Q",
                        "name": "黔东南苗族侗族自治州",
                        "id": 301,
                        "name_ch": "QianDongNanMiaoZuDongZuZiZhiZhou",
                        "shortname_ch": "qdnmzdzzzz"
                    }, {
                        "headChar": "Q",
                        "name": "青岛市",
                        "id": 171,
                        "name_ch": "QingDaoShi",
                        "shortname_ch": "qds"
                    }, {
                        "headChar": "Q",
                        "name": "秦皇岛市",
                        "id": 39,
                        "name_ch": "QinHuangDaoShi",
                        "shortname_ch": "qhds"
                    }, {
                        "headChar": "Q",
                        "name": "曲靖市",
                        "id": 304,
                        "name_ch": "QuJingShi",
                        "shortname_ch": "qjs"
                    }, {
                        "headChar": "Q",
                        "name": "黔南布依族苗族自治州",
                        "id": 302,
                        "name_ch": "QianNanBuYiZuMiaoZuZiZhiZhou",
                        "shortname_ch": "qnbyzmzzzz"
                    }, {
                        "headChar": "Q",
                        "name": "齐齐哈尔市",
                        "id": 95,
                        "name_ch": "QiQiHaErShi",
                        "shortname_ch": "qqhes"
                    }, {
                        "headChar": "Q",
                        "name": "七台河市",
                        "id": 102,
                        "name_ch": "QiTaiHeShi",
                        "shortname_ch": "qths"
                    }, {
                        "headChar": "Q",
                        "name": "黔西南布依族苗族自治州",
                        "id": 299,
                        "name_ch": "QianXiNanBuYiZuMiaoZuZiZhiZhou",
                        "shortname_ch": "qxnbyzmzzzz"
                    }, {
                        "headChar": "Q",
                        "name": "庆阳市",
                        "id": 345,
                        "name_ch": "QingYangShi",
                        "shortname_ch": "qys"
                    }, {
                        "headChar": "Q",
                        "name": "清远市",
                        "id": 247,
                        "name_ch": "QingYuanShi",
                        "shortname_ch": "qys"
                    }, {
                        "headChar": "Q",
                        "name": "钦州市",
                        "id": 259,
                        "name_ch": "QinZhouShi",
                        "shortname_ch": "qzs"
                    }, {
                        "headChar": "Q",
                        "name": "衢州市",
                        "id": 129,
                        "name_ch": "QuZhouShi",
                        "shortname_ch": "qzs"
                    }, {"headChar": "Q", "name": "泉州市", "id": 154, "name_ch": "QuanZhouShi", "shortname_ch": "qzs"}]
                }, {
                    "headChar": "R",
                    "list": [{
                        "headChar": "R",
                        "name": "日喀则地区",
                        "id": 322,
                        "name_ch": "RiKaZeDiQu",
                        "shortname_ch": "rkzdq"
                    }, {"headChar": "R", "name": "日照市", "id": 180, "name_ch": "RiZhaoShi", "shortname_ch": "rzs"}]
                }, {
                    "headChar": "S",
                    "list": [{
                        "headChar": "S",
                        "name": "韶关市",
                        "id": 233,
                        "name_ch": "ShaoGuanShi",
                        "shortname_ch": "sgs"
                    }, {
                        "headChar": "S",
                        "name": "绥化市",
                        "id": 105,
                        "name_ch": "SuiHuaShi",
                        "shortname_ch": "shs"
                    }, {
                        "headChar": "S",
                        "name": "上海市",
                        "id": 389,
                        "name_ch": "ShangHaiShi",
                        "shortname_ch": "shs"
                    }, {
                        "headChar": "S",
                        "name": "石家庄市",
                        "id": 37,
                        "name_ch": "ShiJiaZhuangShi",
                        "shortname_ch": "sjzs"
                    }, {
                        "headChar": "S",
                        "name": "商洛市",
                        "id": 335,
                        "name_ch": "ShangLuoShi",
                        "shortname_ch": "sls"
                    }, {
                        "headChar": "S",
                        "name": "厦门市",
                        "id": 151,
                        "name_ch": "ShaMenShi",
                        "shortname_ch": "sms"
                    }, {
                        "headChar": "S",
                        "name": "三明市",
                        "id": 153,
                        "name_ch": "SanMingShi",
                        "shortname_ch": "sms"
                    }, {
                        "headChar": "S",
                        "name": "三门峡市",
                        "id": 198,
                        "name_ch": "SanMenXiaShi",
                        "shortname_ch": "smxs"
                    }, {
                        "headChar": "S",
                        "name": "山南地区",
                        "id": 321,
                        "name_ch": "ShanNanDiQu",
                        "shortname_ch": "sndq"
                    }, {
                        "headChar": "S",
                        "name": "遂宁市",
                        "id": 280,
                        "name_ch": "SuiNingShi",
                        "shortname_ch": "sns"
                    }, {
                        "headChar": "S",
                        "name": "四平市",
                        "id": 87,
                        "name_ch": "SiPingShi",
                        "shortname_ch": "sps"
                    }, {
                        "headChar": "S",
                        "name": "宿迁市",
                        "id": 121,
                        "name_ch": "SuQianShi",
                        "shortname_ch": "sqs"
                    }, {
                        "headChar": "S",
                        "name": "商丘市",
                        "id": 200,
                        "name_ch": "ShangQiuShi",
                        "shortname_ch": "sqs"
                    }, {
                        "headChar": "S",
                        "name": "上饶市",
                        "id": 169,
                        "name_ch": "ShangRaoShi",
                        "shortname_ch": "srs"
                    }, {
                        "headChar": "S",
                        "name": "汕头市",
                        "id": 236,
                        "name_ch": "ShanTouShi",
                        "shortname_ch": "sts"
                    }, {
                        "headChar": "S",
                        "name": "汕尾市",
                        "id": 244,
                        "name_ch": "ShanWeiShi",
                        "shortname_ch": "sws"
                    }, {
                        "headChar": "S",
                        "name": "绍兴市",
                        "id": 127,
                        "name_ch": "ShaoXingShi",
                        "shortname_ch": "sxs"
                    }, {
                        "headChar": "S",
                        "name": "三亚市",
                        "id": 268,
                        "name_ch": "SanYaShi",
                        "shortname_ch": "sys"
                    }, {
                        "headChar": "S",
                        "name": "沈阳市",
                        "id": 71,
                        "name_ch": "ShenYangShi",
                        "shortname_ch": "sys"
                    }, {
                        "headChar": "S",
                        "name": "松原市",
                        "id": 91,
                        "name_ch": "SongYuanShi",
                        "shortname_ch": "sys"
                    }, {
                        "headChar": "S",
                        "name": "十堰市",
                        "id": 206,
                        "name_ch": "ShiYanShi",
                        "shortname_ch": "sys"
                    }, {
                        "headChar": "S",
                        "name": "邵阳市",
                        "id": 222,
                        "name_ch": "ShaoYangShi",
                        "shortname_ch": "sys"
                    }, {
                        "headChar": "S",
                        "name": "双鸭山市",
                        "id": 98,
                        "name_ch": "ShuangYaShanShi",
                        "shortname_ch": "syss"
                    }, {
                        "headChar": "S",
                        "name": "朔州市",
                        "id": 53,
                        "name_ch": "ShuoZhouShi",
                        "shortname_ch": "szs"
                    }, {
                        "headChar": "S",
                        "name": "苏州市",
                        "id": 113,
                        "name_ch": "SuZhouShi",
                        "shortname_ch": "szs"
                    }, {
                        "headChar": "S",
                        "name": "宿州市",
                        "id": 144,
                        "name_ch": "SuZhouShi",
                        "shortname_ch": "szs"
                    }, {
                        "headChar": "S",
                        "name": "随州市",
                        "id": 215,
                        "name_ch": "SuiZhouShi",
                        "shortname_ch": "szs"
                    }, {
                        "headChar": "S",
                        "name": "深圳市",
                        "id": 234,
                        "name_ch": "ShenZhenShi",
                        "shortname_ch": "szs"
                    }, {
                        "headChar": "S",
                        "name": "石嘴山市",
                        "id": 359,
                        "name_ch": "ShiZuiShanShi",
                        "shortname_ch": "szss"
                    }]
                }, {
                    "headChar": "T",
                    "list": [{
                        "headChar": "T",
                        "name": "泰安市",
                        "id": 178,
                        "name_ch": "TaiAnShi",
                        "shortname_ch": "tas"
                    }, {
                        "headChar": "T",
                        "name": "塔城地区",
                        "id": 375,
                        "name_ch": "TaChengDiQu",
                        "shortname_ch": "tcdq"
                    }, {
                        "headChar": "T",
                        "name": "铜川市",
                        "id": 327,
                        "name_ch": "TongChuanShi",
                        "shortname_ch": "tcs"
                    }, {
                        "headChar": "T",
                        "name": "通化市",
                        "id": 89,
                        "name_ch": "TongHuaShi",
                        "shortname_ch": "ths"
                    }, {
                        "headChar": "T",
                        "name": "天津市",
                        "id": 388,
                        "name_ch": "TianJinShi",
                        "shortname_ch": "tjs"
                    }, {
                        "headChar": "T",
                        "name": "吐鲁番地区",
                        "id": 365,
                        "name_ch": "TuLuFanDiQu",
                        "shortname_ch": "tlfdq"
                    }, {
                        "headChar": "T",
                        "name": "通辽市",
                        "id": 63,
                        "name_ch": "TongLiaoShi",
                        "shortname_ch": "tls"
                    }, {
                        "headChar": "T",
                        "name": "铁岭市",
                        "id": 82,
                        "name_ch": "TieLingShi",
                        "shortname_ch": "tls"
                    }, {
                        "headChar": "T",
                        "name": "铜陵市",
                        "id": 139,
                        "name_ch": "TongLingShi",
                        "shortname_ch": "tls"
                    }, {
                        "headChar": "T",
                        "name": "铜仁地区",
                        "id": 298,
                        "name_ch": "TongRenDiQu",
                        "shortname_ch": "trdq"
                    }, {
                        "headChar": "T",
                        "name": "唐山市",
                        "id": 38,
                        "name_ch": "TangShanShi",
                        "shortname_ch": "tss"
                    }, {
                        "headChar": "T",
                        "name": "天水市",
                        "id": 340,
                        "name_ch": "TianShuiShi",
                        "shortname_ch": "tss"
                    }, {
                        "headChar": "T",
                        "name": "太原市",
                        "id": 48,
                        "name_ch": "TaiYuanShi",
                        "shortname_ch": "tys"
                    }, {
                        "headChar": "T",
                        "name": "泰州市",
                        "id": 120,
                        "name_ch": "TaiZhouShi",
                        "shortname_ch": "tzs"
                    }, {"headChar": "T", "name": "台州市", "id": 131, "name_ch": "TaiZhouShi", "shortname_ch": "tzs"}]
                }, {
                    "headChar": "W",
                    "list": [{
                        "headChar": "W",
                        "name": "潍坊市",
                        "id": 176,
                        "name_ch": "WeiFangShi",
                        "shortname_ch": "wfs"
                    }, {
                        "headChar": "W",
                        "name": "乌海市",
                        "id": 61,
                        "name_ch": "WuHaiShi",
                        "shortname_ch": "whs"
                    }, {
                        "headChar": "W",
                        "name": "芜湖市",
                        "id": 134,
                        "name_ch": "WuHuShi",
                        "shortname_ch": "whs"
                    }, {
                        "headChar": "W",
                        "name": "威海市",
                        "id": 179,
                        "name_ch": "WeiHaiShi",
                        "shortname_ch": "whs"
                    }, {
                        "headChar": "W",
                        "name": "武汉市",
                        "id": 204,
                        "name_ch": "WuHanShi",
                        "shortname_ch": "whs"
                    }, {
                        "headChar": "W",
                        "name": "乌兰察布市",
                        "id": 67,
                        "name_ch": "WuLanChaBuShi",
                        "shortname_ch": "wlcbs"
                    }, {
                        "headChar": "W",
                        "name": "乌鲁木齐市",
                        "id": 363,
                        "name_ch": "WuLuMuQiShi",
                        "shortname_ch": "wlmqs"
                    }, {
                        "headChar": "W",
                        "name": "渭南市",
                        "id": 330,
                        "name_ch": "WeiNanShi",
                        "shortname_ch": "wns"
                    }, {
                        "headChar": "W",
                        "name": "文山壮族苗族自治州",
                        "id": 313,
                        "name_ch": "WenShanZhuangZuMiaoZuZiZhiZhou",
                        "shortname_ch": "wszzmzzzz"
                    }, {
                        "headChar": "W",
                        "name": "武威市",
                        "id": 341,
                        "name_ch": "WuWeiShi",
                        "shortname_ch": "wws"
                    }, {
                        "headChar": "W",
                        "name": "无锡市",
                        "id": 110,
                        "name_ch": "WuXiShi",
                        "shortname_ch": "wxs"
                    }, {
                        "headChar": "W",
                        "name": "梧州市",
                        "id": 256,
                        "name_ch": "WuZhouShi",
                        "shortname_ch": "wzs"
                    }, {
                        "headChar": "W",
                        "name": "吴忠市",
                        "id": 360,
                        "name_ch": "WuZhongShi",
                        "shortname_ch": "wzs"
                    }, {"headChar": "W", "name": "温州市", "id": 124, "name_ch": "WenZhouShi", "shortname_ch": "wzs"}]
                }, {
                    "headChar": "X",
                    "list": [{
                        "headChar": "X",
                        "name": "兴安盟",
                        "id": 68,
                        "name_ch": "XingAnMeng",
                        "shortname_ch": "xam"
                    }, {
                        "headChar": "X",
                        "name": "西安市",
                        "id": 326,
                        "name_ch": "XiAnShi",
                        "shortname_ch": "xas"
                    }, {
                        "headChar": "X",
                        "name": "宣城市",
                        "id": 149,
                        "name_ch": "XuanChengShi",
                        "shortname_ch": "xcs"
                    }, {
                        "headChar": "X",
                        "name": "许昌市",
                        "id": 196,
                        "name_ch": "XuChangShi",
                        "shortname_ch": "xcs"
                    }, {
                        "headChar": "X",
                        "name": "襄樊市",
                        "id": 208,
                        "name_ch": "XiangFanShi",
                        "shortname_ch": "xfs"
                    }, {
                        "headChar": "X",
                        "name": "孝感市",
                        "id": 211,
                        "name_ch": "XiaoGanShi",
                        "shortname_ch": "xgs"
                    }, {
                        "headChar": "X",
                        "name": "锡林郭勒盟",
                        "id": 69,
                        "name_ch": "XiLinGuoLeMeng",
                        "shortname_ch": "xlglm"
                    }, {
                        "headChar": "X",
                        "name": "西宁市",
                        "id": 350,
                        "name_ch": "XiNingShi",
                        "shortname_ch": "xns"
                    }, {
                        "headChar": "X",
                        "name": "咸宁市",
                        "id": 214,
                        "name_ch": "XianNingShi",
                        "shortname_ch": "xns"
                    }, {
                        "headChar": "X",
                        "name": "西双版纳傣族自治州",
                        "id": 314,
                        "name_ch": "XiShuangBanNaDaiZuZiZhiZhou",
                        "shortname_ch": "xsbndzzzz"
                    }, {
                        "headChar": "X",
                        "name": "邢台市",
                        "id": 41,
                        "name_ch": "XingTaiShi",
                        "shortname_ch": "xts"
                    }, {
                        "headChar": "X",
                        "name": "湘潭市",
                        "id": 220,
                        "name_ch": "XiangTanShi",
                        "shortname_ch": "xts"
                    }, {
                        "headChar": "X",
                        "name": "新乡市",
                        "id": 193,
                        "name_ch": "XinXiangShi",
                        "shortname_ch": "xxs"
                    }, {
                        "headChar": "X",
                        "name": "湘西土家族苗族自治州",
                        "id": 231,
                        "name_ch": "XiangXiTuJiaZuMiaoZuZiZhiZhou",
                        "shortname_ch": "xxtjzmzzzz"
                    }, {
                        "headChar": "X",
                        "name": "咸阳市",
                        "id": 329,
                        "name_ch": "XianYangShi",
                        "shortname_ch": "xys"
                    }, {
                        "headChar": "X",
                        "name": "新余市",
                        "id": 163,
                        "name_ch": "XinYuShi",
                        "shortname_ch": "xys"
                    }, {
                        "headChar": "X",
                        "name": "信阳市",
                        "id": 201,
                        "name_ch": "XinYangShi",
                        "shortname_ch": "xys"
                    }, {
                        "headChar": "X",
                        "name": "忻州市",
                        "id": 56,
                        "name_ch": "XinZhouShi",
                        "shortname_ch": "xzs"
                    }, {"headChar": "X", "name": "徐州市", "id": 111, "name_ch": "XuZhouShi", "shortname_ch": "xzs"}]
                }, {
                    "headChar": "Y",
                    "list": [{
                        "headChar": "Y",
                        "name": "雅安市",
                        "id": 288,
                        "name_ch": "YaAnShi",
                        "shortname_ch": "yas"
                    }, {
                        "headChar": "Y",
                        "name": "延安市",
                        "id": 331,
                        "name_ch": "YanAnShi",
                        "shortname_ch": "yas"
                    }, {
                        "headChar": "Y",
                        "name": "延边朝鲜族自治州",
                        "id": 93,
                        "name_ch": "YanBianChaoXianZuZiZhiZhou",
                        "shortname_ch": "ybcxzzzz"
                    }, {
                        "headChar": "Y",
                        "name": "宜宾市",
                        "id": 285,
                        "name_ch": "YiBinShi",
                        "shortname_ch": "ybs"
                    }, {
                        "headChar": "Y",
                        "name": "运城市",
                        "id": 55,
                        "name_ch": "YunChengShi",
                        "shortname_ch": "ycs"
                    }, {
                        "headChar": "Y",
                        "name": "伊春市",
                        "id": 100,
                        "name_ch": "YiChunShi",
                        "shortname_ch": "ycs"
                    }, {
                        "headChar": "Y",
                        "name": "银川市",
                        "id": 358,
                        "name_ch": "YinChuanShi",
                        "shortname_ch": "ycs"
                    }, {
                        "headChar": "Y",
                        "name": "盐城市",
                        "id": 117,
                        "name_ch": "YanChengShi",
                        "shortname_ch": "ycs"
                    }, {
                        "headChar": "Y",
                        "name": "宜春市",
                        "id": 167,
                        "name_ch": "YiChunShi",
                        "shortname_ch": "ycs"
                    }, {
                        "headChar": "Y",
                        "name": "宜昌市",
                        "id": 207,
                        "name_ch": "YiChangShi",
                        "shortname_ch": "ycs"
                    }, {
                        "headChar": "Y",
                        "name": "云浮市",
                        "id": 252,
                        "name_ch": "YunFuShi",
                        "shortname_ch": "yfs"
                    }, {
                        "headChar": "Y",
                        "name": "阳江市",
                        "id": 246,
                        "name_ch": "YangJiangShi",
                        "shortname_ch": "yjs"
                    }, {
                        "headChar": "Y",
                        "name": "营口市",
                        "id": 78,
                        "name_ch": "YingKouShi",
                        "shortname_ch": "yks"
                    }, {
                        "headChar": "Y",
                        "name": "伊犁哈萨克自治州",
                        "id": 374,
                        "name_ch": "YiLiHaSaKeZiZhiZhou",
                        "shortname_ch": "ylhskzzz"
                    }, {
                        "headChar": "Y",
                        "name": "玉林市",
                        "id": 261,
                        "name_ch": "YuLinShi",
                        "shortname_ch": "yls"
                    }, {
                        "headChar": "Y",
                        "name": "榆林市",
                        "id": 333,
                        "name_ch": "YuLinShi",
                        "shortname_ch": "yls"
                    }, {
                        "headChar": "Y",
                        "name": "阳泉市",
                        "id": 50,
                        "name_ch": "YangQuanShi",
                        "shortname_ch": "yqs"
                    }, {
                        "headChar": "Y",
                        "name": "玉树藏族自治州",
                        "id": 356,
                        "name_ch": "YuShuZangZuZiZhiZhou",
                        "shortname_ch": "yszzzzz"
                    }, {
                        "headChar": "Y",
                        "name": "鹰潭市",
                        "id": 164,
                        "name_ch": "YingTanShi",
                        "shortname_ch": "yts"
                    }, {
                        "headChar": "Y",
                        "name": "烟台市",
                        "id": 175,
                        "name_ch": "YanTaiShi",
                        "shortname_ch": "yts"
                    }, {
                        "headChar": "Y",
                        "name": "玉溪市",
                        "id": 305,
                        "name_ch": "YuXiShi",
                        "shortname_ch": "yxs"
                    }, {
                        "headChar": "Y",
                        "name": "岳阳市",
                        "id": 223,
                        "name_ch": "YueYangShi",
                        "shortname_ch": "yys"
                    }, {
                        "headChar": "Y",
                        "name": "益阳市",
                        "id": 226,
                        "name_ch": "YiYangShi",
                        "shortname_ch": "yys"
                    }, {
                        "headChar": "Y",
                        "name": "扬州市",
                        "id": 118,
                        "name_ch": "YangZhouShi",
                        "shortname_ch": "yzs"
                    }, {"headChar": "Y", "name": "永州市", "id": 228, "name_ch": "YongZhouShi", "shortname_ch": "yzs"}]
                }, {
                    "headChar": "Z",
                    "list": [{
                        "headChar": "Z",
                        "name": "淄博市",
                        "id": 172,
                        "name_ch": "ZiBoShi",
                        "shortname_ch": "zbs"
                    }, {
                        "headChar": "Z",
                        "name": "长春市",
                        "id": 85,
                        "name_ch": "ZhangChunShi",
                        "shortname_ch": "zcs"
                    }, {
                        "headChar": "Z",
                        "name": "自贡市",
                        "id": 274,
                        "name_ch": "ZiGongShi",
                        "shortname_ch": "zgs"
                    }, {
                        "headChar": "Z",
                        "name": "珠海市",
                        "id": 235,
                        "name_ch": "ZhuHaiShi",
                        "shortname_ch": "zhs"
                    }, {
                        "headChar": "Z",
                        "name": "张家界市",
                        "id": 225,
                        "name_ch": "ZhangJiaJieShi",
                        "shortname_ch": "zjjs"
                    }, {
                        "headChar": "Z",
                        "name": "张家口市",
                        "id": 43,
                        "name_ch": "ZhangJiaKouShi",
                        "shortname_ch": "zjks"
                    }, {
                        "headChar": "Z",
                        "name": "镇江市",
                        "id": 119,
                        "name_ch": "ZhenJiangShi",
                        "shortname_ch": "zjs"
                    }, {
                        "headChar": "Z",
                        "name": "湛江市",
                        "id": 239,
                        "name_ch": "ZhanJiangShi",
                        "shortname_ch": "zjs"
                    }, {
                        "headChar": "Z",
                        "name": "周口市",
                        "id": 202,
                        "name_ch": "ZhouKouShi",
                        "shortname_ch": "zks"
                    }, {
                        "headChar": "Z",
                        "name": "驻马店市",
                        "id": 203,
                        "name_ch": "ZhuMaDianShi",
                        "shortname_ch": "zmds"
                    }, {
                        "headChar": "Z",
                        "name": "肇庆市",
                        "id": 241,
                        "name_ch": "ZhaoQingShi",
                        "shortname_ch": "zqs"
                    }, {
                        "headChar": "Z",
                        "name": "舟山市",
                        "id": 130,
                        "name_ch": "ZhouShanShi",
                        "shortname_ch": "zss"
                    }, {
                        "headChar": "Z",
                        "name": "长沙市",
                        "id": 218,
                        "name_ch": "ZhangShaShi",
                        "shortname_ch": "zss"
                    }, {
                        "headChar": "Z",
                        "name": "中山市",
                        "id": 249,
                        "name_ch": "ZhongShanShi",
                        "shortname_ch": "zss"
                    }, {
                        "headChar": "Z",
                        "name": "昭通市",
                        "id": 307,
                        "name_ch": "ZhaoTongShi",
                        "shortname_ch": "zts"
                    }, {
                        "headChar": "Z",
                        "name": "中卫市",
                        "id": 362,
                        "name_ch": "ZhongWeiShi",
                        "shortname_ch": "zws"
                    }, {
                        "headChar": "Z",
                        "name": "资阳市",
                        "id": 290,
                        "name_ch": "ZiYangShi",
                        "shortname_ch": "zys"
                    }, {
                        "headChar": "Z",
                        "name": "遵义市",
                        "id": 296,
                        "name_ch": "ZunYiShi",
                        "shortname_ch": "zys"
                    }, {
                        "headChar": "Z",
                        "name": "张掖市",
                        "id": 342,
                        "name_ch": "ZhangYeShi",
                        "shortname_ch": "zys"
                    }, {
                        "headChar": "Z",
                        "name": "长治市",
                        "id": 51,
                        "name_ch": "ZhangZhiShi",
                        "shortname_ch": "zzs"
                    }, {
                        "headChar": "Z",
                        "name": "漳州市",
                        "id": 155,
                        "name_ch": "ZhangZhouShi",
                        "shortname_ch": "zzs"
                    }, {
                        "headChar": "Z",
                        "name": "枣庄市",
                        "id": 173,
                        "name_ch": "ZaoZhuangShi",
                        "shortname_ch": "zzs"
                    }, {
                        "headChar": "Z",
                        "name": "郑州市",
                        "id": 187,
                        "name_ch": "ZhengZhouShi",
                        "shortname_ch": "zzs"
                    }, {"headChar": "Z", "name": "株洲市", "id": 219, "name_ch": "ZhuZhouShi", "shortname_ch": "zzs"}]
                }],
                dta: ['a', 'b', 'c', 'd', 'f']
            }
        },
        methods: {
            cityExchange(data) {
                for (let i = 0; i < data.length; i++) {
                    this.cityLetter.push(data[i].headChar);
                    this.letterToCity[data[i].headChar] = data[i].list;
                }
            },
            letterClick(item) {
                const offsetTop = document.querySelector('#' + item).offsetTop;
                document.documentElement.scrollTop = offsetTop;
                document.body.scrollTop = offsetTop;
            },
            collectOffsetTop() {

                // 每一个区域应该是它的offsetTop + clientHeight

                for (let i of this.cityLetter) {
                    const a = document.querySelector('#' + i).offsetTop;
                    const b = document.querySelector('#' + i + '-1').clientHeight / 2;
                    const c = document.querySelector('#' + i + '-2').offsetTop;
                    const d = document.querySelector('#' + i + '-2').clientHeight;
                    this.offsetTops.push(a + b);
                    this.letterOTS.push(c + d);
                }
            },
            letterGTMove($event) {

                //  todo 这里有个问题就是手指移动过程中会出现页面的上下滑动 所谓的 穿透问题

                const a = parseInt($event.touches[0].pageY);
                for (let i in this.letterOTS) {
                    if (a < this.letterOTS[i]) {
                        console.log(i, this.cityLetter[i]);
                        // this.letterClick(this.cityLetter[i]);
                        // this.letterActive = this.cityLetter[i、];
                        return;
                    }
                }
            },
        },
        mounted() {
            const _this = this;
            this.cityExchange(this.cityD);
            this.$nextTick(function () {
                this.collectOffsetTop();
                window.onscroll = window.ontouchmove = function () {
                    _this.showLetterA = true;
                    const scrollTop = document.documentElement.scrollTop || document.body.scrollTop;
                    for (let i = 0; i < _this.offsetTops.length; i++) {
                        if (scrollTop < _this.offsetTops[i]) {
                            _this.letterActive = _this.cityLetter[i];
                            return;
                        }
                    }
                };
            });
        }
    }
</script>

<style lang="stylus" type="text/stylus">
    .citySwitch
        position relative
        width 100%
        .innerCitySwitch
            position relative
            z-index 0
            .listCity
                position relative
                z-index 0
                .title
                    padding .5rem
                    font-size .8rem
                .item
                    font-size .7rem
                    .lcTitle
                        padding 0 .5rem
                        background #f5f5f5
                    .lcItem
                        padding .5rem
                        border-bottom 1px solid #eee
                        &:last-child
                            border-bottom 0
        .letterGuide
            display flex
            position fixed
            top 0
            right 0
            align-items center
            justify-content center
            height 100%
            background aqua
            z-index 99
        .letterActive
            display flex
            position fixed
            width 4rem
            height 4rem
            align-items center
            justify-content center
            top 0
            left 0
            right 0
            bottom 0
            margin auto
            border-radius 50%
            color #ffffff
            font-size 1rem
            background #000000
            z-index 99
</style>
