<template>
    <div class="idPidD">
        idPidD
    </div>
</template>

<script>
    export default {
        name: 'idPidD',
        data() {
            return {
                idPid: [{
                    "level": "1",
                    "name": "眼部",
                    "subNav": [{
                        "level": "2",
                        "name": "双眼皮",
                        "subNav": [],
                        "weight": 99,
                        "id": 16,
                        "synonymName": ""
                    }, {
                        "level": "2",
                        "name": "眼角开大",
                        "subNav": [],
                        "weight": 99,
                        "id": 17,
                        "synonymName": ""
                    }, {
                        "level": "2",
                        "name": "上睑下垂",
                        "subNav": [],
                        "weight": 99,
                        "id": 18,
                        "synonymName": ""
                    }, {
                        "level": "2",
                        "name": "眼袋",
                        "subNav": [],
                        "weight": 99,
                        "id": 19,
                        "synonymName": ""
                    }, {
                        "level": "2",
                        "name": "黑眼圈",
                        "subNav": [],
                        "weight": 99,
                        "id": 20,
                        "synonymName": ""
                    }, {"level": "2", "name": "眼综合", "subNav": [], "weight": 99, "id": 21, "synonymName": ""}],
                    "weight": 99,
                    "id": 1,
                    "synonymName": ""
                }, {
                    "level": "1",
                    "name": "鼻部",
                    "subNav": [{
                        "level": "2",
                        "name": "鼻综合",
                        "subNav": [],
                        "weight": 99,
                        "id": 22,
                        "synonymName": ""
                    }, {
                        "level": "2",
                        "name": "隆鼻",
                        "subNav": [],
                        "weight": 99,
                        "id": 23,
                        "synonymName": ""
                    }, {"level": "2", "name": "鼻部整形", "subNav": [], "weight": 99, "id": 24, "synonymName": ""}],
                    "weight": 99,
                    "id": 2,
                    "synonymName": ""
                }, {
                    "level": "1",
                    "name": "面部轮廓",
                    "subNav": [{
                        "level": "2",
                        "name": "小V脸",
                        "subNav": [],
                        "weight": 99,
                        "id": 25,
                        "synonymName": ""
                    }, {"level": "2", "name": "颅颌面", "subNav": [], "weight": 99, "id": 26, "synonymName": ""}],
                    "weight": 99,
                    "id": 3,
                    "synonymName": ""
                }, {
                    "level": "1",
                    "name": "胸部",
                    "subNav": [{
                        "level": "2",
                        "name": "乳房下垂",
                        "subNav": [],
                        "weight": 99,
                        "id": 27,
                        "synonymName": ""
                    }, {
                        "level": "2",
                        "name": "乳晕",
                        "subNav": [],
                        "weight": 99,
                        "id": 28,
                        "synonymName": ""
                    }, {
                        "level": "2",
                        "name": "乳头",
                        "subNav": [],
                        "weight": 99,
                        "id": 29,
                        "synonymName": ""
                    }, {"level": "2", "name": "隆胸", "subNav": [], "weight": 99, "id": 52, "synonymName": ""}],
                    "weight": 99,
                    "id": 4,
                    "synonymName": ""
                }, {
                    "level": "1",
                    "name": "自体脂肪",
                    "subNav": [{
                        "level": "2",
                        "name": "面部脂肪填充",
                        "subNav": [],
                        "weight": 99,
                        "id": 30,
                        "synonymName": ""
                    }, {"level": "2", "name": "抽脂", "subNav": [], "weight": 99, "id": 31, "synonymName": ""}],
                    "weight": 99,
                    "id": 5,
                    "synonymName": ""
                }, {
                    "level": "1",
                    "name": "私密整形",
                    "subNav": [{
                        "level": "2",
                        "name": "手术",
                        "subNav": [],
                        "weight": 99,
                        "id": 53,
                        "synonymName": ""
                    }, {
                        "level": "2",
                        "name": "微创",
                        "subNav": [],
                        "weight": 99,
                        "id": 54,
                        "synonymName": ""
                    }, {"level": "2", "name": "激光", "subNav": [], "weight": 99, "id": 55, "synonymName": ""}],
                    "weight": 99,
                    "id": 6,
                    "synonymName": ""
                }, {
                    "level": "1",
                    "name": "皮肤",
                    "subNav": [{
                        "level": "2",
                        "name": "抗初老",
                        "subNav": [],
                        "weight": 99,
                        "id": 33,
                        "synonymName": ""
                    }, {
                        "level": "2",
                        "name": "美白",
                        "subNav": [],
                        "weight": 99,
                        "id": 34,
                        "synonymName": ""
                    }, {
                        "level": "2",
                        "name": "补水",
                        "subNav": [],
                        "weight": 99,
                        "id": 35,
                        "synonymName": ""
                    }, {
                        "level": "2",
                        "name": "激光",
                        "subNav": [],
                        "weight": 99,
                        "id": 36,
                        "synonymName": ""
                    }, {
                        "level": "2",
                        "name": "祛斑",
                        "subNav": [],
                        "weight": 99,
                        "id": 37,
                        "synonymName": ""
                    }, {
                        "level": "2",
                        "name": "祛痘",
                        "subNav": [],
                        "weight": 99,
                        "id": 38,
                        "synonymName": ""
                    }, {"level": "2", "name": "光子嫩肤", "subNav": [], "weight": 99, "id": 39, "synonymName": ""}],
                    "weight": 99,
                    "id": 7,
                    "synonymName": ""
                }, {
                    "level": "1",
                    "name": "半永久",
                    "subNav": [{
                        "level": "2",
                        "name": "半永久妆",
                        "subNav": [],
                        "weight": 99,
                        "id": 40,
                        "synonymName": ""
                    }],
                    "weight": 99,
                    "id": 8,
                    "synonymName": ""
                }, {
                    "level": "1",
                    "name": "修复",
                    "subNav": [{
                        "level": "2",
                        "name": "外伤修复",
                        "subNav": [],
                        "weight": 99,
                        "id": 41,
                        "synonymName": ""
                    }],
                    "weight": 99,
                    "id": 9,
                    "synonymName": ""
                }, {
                    "level": "1",
                    "name": "微整注射",
                    "subNav": [{
                        "level": "2",
                        "name": "抗衰老",
                        "subNav": [],
                        "weight": 99,
                        "id": 42,
                        "synonymName": ""
                    }, {
                        "level": "2",
                        "name": "肉毒素",
                        "subNav": [],
                        "weight": 99,
                        "id": 43,
                        "synonymName": ""
                    }, {"level": "2", "name": "玻尿酸", "subNav": [], "weight": 99, "id": 44, "synonymName": ""}],
                    "weight": 99,
                    "id": 10,
                    "synonymName": ""
                }, {
                    "level": "1",
                    "name": "唇部",
                    "subNav": [],
                    "weight": 99,
                    "id": 11,
                    "synonymName": ""
                }, {
                    "level": "1",
                    "name": "毛发",
                    "subNav": [{
                        "level": "2",
                        "name": "毛发稀少",
                        "subNav": [],
                        "weight": 99,
                        "id": 45,
                        "synonymName": ""
                    }, {"level": "2", "name": "激光脱毛", "subNav": [], "weight": 99, "id": 46, "synonymName": ""}],
                    "weight": 99,
                    "id": 12,
                    "synonymName": ""
                }, {
                    "level": "1",
                    "name": "美体塑形",
                    "subNav": [{
                        "level": "2",
                        "name": "臀部",
                        "subNav": [],
                        "weight": 99,
                        "id": 48,
                        "synonymName": ""
                    }, {
                        "level": "2",
                        "name": "肚子",
                        "subNav": [],
                        "weight": 99,
                        "id": 49,
                        "synonymName": ""
                    }, {
                        "level": "2",
                        "name": "大腿",
                        "subNav": [],
                        "weight": 99,
                        "id": 50,
                        "synonymName": ""
                    }, {"level": "2", "name": "手臂", "subNav": [], "weight": 99, "id": 51, "synonymName": ""}],
                    "weight": 99,
                    "id": 13,
                    "synonymName": ""
                }]
            }

        },
    }
</script>

<style>

</style>
